import type { ProtectionReportInput } from "./types";

/**
 * Illustrative protection portfolio for development and report layout previews.
 * Fictional household and policy data — not real client information.
 * Figures align with the reference report structure (4 policies, ILP allocation, KPI totals).
 */
export const sampleProtectionReport: ProtectionReportInput = {
  household: {
    householdName: "The Mercer Family",
    primaryContact: "James Mercer",
    statementPeriod: "May 2026",
    adviserName: "Eleanor Vance",
    adviserCompany: "AEGIS Private Advisory",
  },
  insuredPersons: [
    {
      id: "person-james",
      fullName: "James Mercer",
      relationship: "Self",
      age: 38,
      healthNotes: "Primary income earner",
    },
    {
      id: "person-sarah",
      fullName: "Sarah Mercer",
      relationship: "Spouse",
      age: 36,
      healthNotes: "Part-time employment; eczema history",
    },
    {
      id: "person-noah",
      fullName: "Noah Mercer",
      relationship: "Son",
      age: 8,
      healthNotes: "Healthy",
    },
    {
      id: "person-lily",
      fullName: "Lily Mercer",
      relationship: "Daughter",
      age: 5,
      healthNotes: "Healthy",
    },
  ],
  policies: [
    {
      id: "policy-whole-life",
      insuredPersonId: "person-james",
      planName: "Atlas Active Life",
      insurer: "Sentinel Assurance",
      policyType: "Whole Life",
      policyNumber: "SAL-WL-88421",
      sumAssured: 1_000_000,
      monthlyPremium: 580,
      annualPremium: 6_960,
      currentValue: 18_200,
      paidToDate: 27_840,
      whatItCovers: "Death, TPD, CI (Multi-Pay)",
      premiumTerm: "25 years",
      policyTerm: "Whole of Life",
      policyStart: "Mar 2022",
      beneficiary: "Sarah Mercer (100%)",
      projectedValue: "S$1.65M @ age 65",
    },
    {
      id: "policy-hospitalisation",
      insuredPersonId: "person-james",
      planName: "Sentinel Shield Premier + Extra",
      insurer: "Sentinel Assurance",
      policyType: "Hospitalisation (IP)",
      policyNumber: "SAL-IP-55290",
      sumAssured: 0,
      sumAssuredLabel: "As charged",
      monthlyPremium: 320,
      annualPremium: 3_840,
      paidToDate: 23_040,
      whatItCovers: "Hospital, surgical, ICU, A-ward private",
      premiumTerm: "Yearly renewable",
      policyTerm: "Lifetime",
      policyStart: "Jan 2020",
    },
    {
      id: "policy-ilp",
      insuredPersonId: "person-sarah",
      planName: "Atlas Wealth",
      insurer: "Sentinel Assurance",
      policyType: "ILP",
      policyNumber: "SAL-ILP-33107",
      sumAssured: 300_000,
      monthlyPremium: 450,
      annualPremium: 5_400,
      currentValue: 11_280,
      paidToDate: 14_400,
      whatItCovers: "Death + investment growth",
      premiumTerm: "20 years",
      policyTerm: "Whole of Life",
      policyStart: "Sep 2023",
      beneficiary: "James Mercer (100%)",
      projectedValue: "S$280K @ age 60",
    },
    {
      id: "policy-endowment",
      insuredPersonId: "person-noah",
      planName: "Atlas EduSave",
      insurer: "Sentinel Assurance",
      policyType: "Endowment",
      policyNumber: "SAL-ED-11984",
      sumAssured: 100_000,
      monthlyPremium: 180,
      annualPremium: 2_160,
      currentValue: 7_950,
      paidToDate: 8_640,
      whatItCovers: "Education fund + death benefit",
      premiumTerm: "15 years",
      policyTerm: "20 years (matures 2042)",
      policyStart: "Jun 2022",
      beneficiary: "James Mercer & Sarah Mercer",
      projectedValue: "S$105K @ age 22",
    },
  ],
  investmentFunds: [
    {
      id: "fund-global-equity",
      policyId: "policy-ilp",
      fundName: "Atlas Link Global Equity Fund",
      allocationPercent: 60,
      currentValue: 6_768,
    },
    {
      id: "fund-asian-income",
      policyId: "policy-ilp",
      fundName: "Atlas Link Asian Income Fund",
      allocationPercent: 40,
      currentValue: 4_512,
    },
  ],
};
